repos:
  - repo: local
    hooks:
    - id: black
      name: black
      entry: black
      language: python
      types: [python]
      language_version: python3.8
      args: [--line-length=120]
  - repo: local
    hooks:
    - id: mypy
      name: mypy
      entry: mypy
      language: python
      types: [python]
      args: [--ignore-missing-imports, --namespace-packages, --show-error-codes, --pretty]
  - repo: local
    hooks:
    - id: flake8
      name: flake8
      entry: flake8
      language: python
      types: [python]
      args: [--max-line-length=120, --docstring-convention=google, "--ignore=D100,D104,D212,D200,E203,W293,D412,W503"]
# D100 requires all Python files (modules) to have a "public" docstring even if all functions within have a docstring.
# D104 requires __init__ files to have a docstring
# D212
# D200 
# D412 No blank lines allowed between a section header and its content
# E203
# W293 blank line contains whitespace
# W503 line break before binary operator (for compatibility with black)